### ISSUE TITLE
OOTB errors

### ISSUE THREAD

**Issue by dhowellpaxata** [desklabs/Desk.com-CSV-to-Case#3]
Followed instructions exactly as stated.  This is the output of ruby customer_import.rb

customer_import.rb:65: syntax error, unexpected ':', expecting =>
...      address_array << {"type": type, "value": value} unless...
...                               ^
customer_import.rb:65: syntax error, unexpected ':', expecting :: or '[' or '.'
...rray << {"type": type, "value": value} unless value.nil? or ...
...                               ^
customer_import.rb:77: syntax error, unexpected ':', expecting =>
      emails_array << {"type": type, "value": value} unless...
                              ^
customer_import.rb:77: syntax error, unexpected ':', expecting :: or '[' or '.'
...rray << {"type": type, "value": value} unless value.nil? or ...
...                               ^
customer_import.rb:89: syntax error, unexpected ':', expecting =>
      phones_array << {"type": type, "value": value} unless...
                              ^
customer_import.rb:89: syntax error, unexpected ':', expecting :: or '[' or '.'
...rray << {"type": type, "value": value} unless value.nil? or ...
...                               ^

Any suggestions on how to correct this?

**Comment by Skeyelab** [comment]
Hey, is this still happening?  I can look into it today. What is your OS?

**Comment by Skeyelab** [comment]
Not enough info to diagnose.  No response.  Closing the issue.
