### ISSUE TITLE
Question: how to validate customers were created?

### ISSUE THREAD

**Issue by jasonlockporcelane** [desklabs/Desk.com-CSV-to-Case#5]
Hello, 
Had a question about how to validate that new customers are created in Desk after running the customer_import.rb script. Following the steps in Script setup and running the customer_import.rb script outputs:

```
______________________________
Success creating customer: CSV Row: 22, Customer ID: 32
```

but when I go to https://porcelanehq.desk.com/agent I don’t see a new customer record. Is there somewhere else, in the UI that will show the new customers or perhaps a better way to validate that the customer was created?

Here is a sample from the customers.csv: 

```
id,first_name,email_home,custom_fieldkey¬
32,Jason Lock,jason@porcelane.com,Dentist Appointment 
```

Two things that might be worth mentioning; There was some test data already in the account (53 customers). I’m also running the script from docker container that has the required ruby version instead of RVM. 

Thank you for any help!

**Comment by jasonlockporcelane** [comment]
Found them under `/web/agent/search/customers?query=*&page=1&count=2`.

**Comment by Skeyelab** [comment]
It might take a few minutes for Desk to index the new customers.  You can always search for their email address, or to list all customers search for \* via the UI.

Does this help?
