### ISSUE TITLE
DeskApi::Error::ClientError:0x00000004ed0d10

### ISSUE THREAD

**Issue by SilentBlueD666** [desklabs/Desk.com-CSV-to-Case#6]
While trying to import clients I get the error: DeskApi::Error::ClientError:0x00000004ed0d10

![image](https://cloud.githubusercontent.com/assets/13220992/23713966/896e5fa6-041f-11e7-9800-ba0a2dad50d6.png)

**Comment by Skeyelab** [comment]
I just made a change.
can you do a ```git pull``` and try again and let me know?

**Comment by Skeyelab** [comment]
However, I recommend you use this tool instead: https://desk-uploader.herokuapp.com/

Please note there is a minor difference in the CSV spec for that tool around the customer file company_name column.

**Comment by SilentBlueD666** [comment]
Ah I see timing on my part :)

I get an SSL error now:
![image](https://cloud.githubusercontent.com/assets/13220992/23714401/e2747350-0420-11e7-9416-0829728a6b82.png)

But I shall try the other tool

I tried this tool as the documentation on Desk.com https://support.desk.com/customer/portal/articles/2466825?b_id=7112
Might be worth updating the other tool there as well :)

**Comment by SilentBlueD666** [comment]
Just to let you know the other tool worked great! Thanks.

**Comment by Skeyelab** [comment]
@SilentBlueD666 

I think your error is related to OpenSSL on windows.  I do not have a windows machine to test on.
If I were you, I'd google the error.  I found this: http://gnuwin32.sourceforge.net/packages/openssl.htm

Also this: https://gist.github.com/luislavena/f064211759ee0f806c88

Sorry, wish I could help more.

**Comment by SilentBlueD666** [comment]
That's ok I used the other tool so job all done. Thanks again.

________________________________
